version: '3'

services:
  front-end:
    build: ${FRONT_END_PATH}
    image: ${FRONT_END_NAME}:${TAG}
    volumes:
      - type: bind
        source: ${FRONT_END_PATH}
        target: /app
    ports: 
      - ${FRONT_END_PORT}:3000
    expose:
      - ${FRONT_END_PORT}
    # networks:
    #   - dev
    command: "npm start"

  web-server: 
    build: ${WEB_SERVER_PATH}
    image: ${WEB_SERVER_NAME}:${TAG}
    volumes:
      - type: bind
        source: ${WEB_SERVER_PATH}
        target: /app
    ports: 
      - ${WEB_SERVER_PORT}:80
    restart: always
       
    # env_file:
    #   - .env
    # networks:
    #   - dev     
    # command: "uvicorn main:app --host=0.0.0.0 --reload --port=${WEB_SERVER_PORT}"  
  
  recipe-api: 
    build: ${RECIPE_API_PATH}
    image: ${RECIPE_API_NAME}:${TAG}
    volumes:
      - type: bind
        source: ${RECIPE_API_PATH}
        target: /app
    ports: 
      - ${RECIPE_API_PORT}:${RECIPE_API_PORT}  
    expose:
      - ${RECIPE_API_PORT}
    # env_file:
    #   - .env
    # networks:
    #   - dev     
    command: "uvicorn main:app --host=0.0.0.0 --reload --port=${RECIPE_API_PORT}"

  # recipe-scraper: 
  #   build: ${RECIPE_SCRAPER_PATH}
  #   image: ${RECIPE_SCRAPER_NAME}:${TAG}
  #   volumes:
  #     - type: bind
  #       source: ${RECIPE_SCRAPER_PATH}
  #       target: /app
  #   # networks:
  #   #   - dev     
  #   command: "python test.py" 
  #   # TODO: run cron job

  postgres:
    container_name: ${RECIPE_DB_NAME}
    image: postgres
    hostname: ${RECIPE_DB_NAME}
    ports:
      - ${RECIPE_DB_PORT}:${RECIPE_DB_PORT}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TEST_SM
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data:
  
# # networks:
# #   dev: 
    